'use client';
import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {get,post,put,patch} from '@/lib/api';
import {Button,Card,PageHeader,ErrorState,Skeleton} from '@/components/ui';
import type {Page} from '@/types';

type Store={id:number;name:string;addressLine?:string;city:string;pincode:string;latitude?:number;longitude?:number;operatingHoursStart?:string;operatingHoursEnd?:string;capacity:number;active:boolean;warehouseManagerUserId?:number;warehouseManagerEmail?:string};
export default function StoresPage(){
 const qc=useQueryClient(); const [editing,setEditing]=useState<Store|null>(null); const q=useQuery({queryKey:['admin-stores'],queryFn:()=>get<Page<Store>>('/admin/stores?page=0&size=100')});
 const save=useMutation({mutationFn:(s:any)=>s.id?put(`/admin/stores/${s.id}`,s):post('/admin/stores',s),onSuccess:()=>{setEditing(null);qc.invalidateQueries({queryKey:['admin-stores']})}});
 const toggle=useMutation({mutationFn:({id,active}:{id:number;active:boolean})=>patch(`/admin/stores/${id}/active?active=${active}`),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-stores']})});
 const empty={id:0,name:'',addressLine:'',city:'',pincode:'',latitude:28.6139,longitude:77.2090,capacity:100,operatingHoursStart:'08:00',operatingHoursEnd:'23:00',warehouseManagerUserId:''};
 return <><PageHeader title="Stores & warehouses" subtitle="Create stores and assign warehouse-manager users." action={<Button onClick={()=>setEditing(empty as any)}>Create store</Button>}/><Card>{q.isLoading?<div className="p-5"><Skeleton className="h-12"/></div>:q.isError?<ErrorState message={(q.error as Error).message} onRetry={()=>q.refetch()}/>:<div className="divide-y">{q.data?.content.map(s=><div key={s.id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><b>#{s.id} · {s.name}</b><div className="text-sm text-gray-500">{s.city} · capacity {s.capacity}</div><div className="text-xs text-gray-400">Manager: {s.warehouseManagerEmail||'Unassigned'}</div></div><div className="flex gap-2"><Button onClick={()=>setEditing({...s,warehouseManagerUserId:String(s.warehouseManagerUserId||'')} as any)}>Edit</Button><Button onClick={()=>toggle.mutate({id:s.id,active:!s.active})}>{s.active?'Deactivate':'Activate'}</Button></div></div>)}</div>}</Card>{editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-5"><Card className="w-full max-w-2xl p-6"><h2 className="text-xl font-black">{editing.id?'Edit':'Create'} store</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{(['name','addressLine','city','pincode','latitude','longitude','capacity','operatingHoursStart','operatingHoursEnd','warehouseManagerUserId'] as const).map(k=><label key={k} className="text-sm font-semibold">{k}<input value={(editing as any)[k]??''} onChange={e=>setEditing({...editing,[k]:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>)}</div><div className="mt-5 flex justify-end gap-2"><Button onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={save.isPending} onClick={()=>save.mutate({...editing,id:editing.id||undefined,latitude:Number(editing.latitude),longitude:Number(editing.longitude),capacity:Number(editing.capacity),warehouseManagerUserId:editing.warehouseManagerUserId?Number(editing.warehouseManagerUserId):null})}>Save</Button></div></Card></div>}</>}
